version: "2.23.3"

services:
  database:
    image: postgres
    container_name: database_connecthub_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - pgdata:/data/postgres

  api:
    build:
      context: .
    container_name: connecthub_api
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
